name : Auto deploy

on :
  workflow_dispatch:
  push:
    branches:
      - main

jobs :
  deploy :
    runs-on : ubuntu-latest

    steps :
      - name : checkout repository
        uses : actions/checkout@v3
  
      - name: SFTP Deploy
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with :
          username: '${{ secrets.USER_NAME }}'
          server : '${{ secrets.DEV_ELAIP }}'
          ssh_private_key: ${{ secrets.PRIVATE_KEY }}
          local_path : './*'
          remote_path: '/usr/share/nginx/html'
